name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [opened, reopened, synchronize]

jobs:
  build-and-run-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup SonarScanner
      run: dotnet tool install --global dotnet-sonarscanner
    - name: Start Sonar scan
      run: |
        dotnet sonarscanner begin \
          /k:alexander-trishin_personal-website-webapi \
          /o:alexander-trishin \
          /d:sonar.host.url=https://sonarcloud.io \
          /d:sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml \
          /d:sonar.login=${{ secrets.SONAR_TOKEN }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: |
        dotnet test --no-build --verbosity normal \
          -p:CollectCoverage=true \
          -p:CoverletOutputFormat=opencover \
          -p:CoverletOutput=../../coverage/ \
          -p:MergeWith=../../coverage/
    - name: Finish Sonar scan
      run: dotnet sonarscanner end /d:sonar.login=${{ secrets.SONAR_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
