name: Deploy

on:
  workflow_run:
    workflows: [Test]
    types:
      - completed

env:
  APP_NAME: alexander-trishin-webapi

jobs:
  build-docker-and-deploy-to-heroku:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login (docker)
      run: echo ${{ secrets.HEROKU_API_KEY }} | docker login --username=_ --password-stdin registry.heroku.com
    - name: Login (heroku)
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: $APP_NAME
        heroku_email: Alexander_Trishin@mail.ru
        justlogin: true
    - name: Build
      run: docker build -f "source/Ravenhorn.PersonalWebsite.WebApi/Dockerfile" --no-cache -t personalwebsite .
    - name: Push
      run: |
        docker tag personalwebsite registry.heroku.com/$APP_NAME/web
        docker push registry.heroku.com/$APP_NAME/web
    - name: Publish
      run: heroku container:release web --app=$APP_NAME
